### PR TITLE
Pasting general FENs to targeted variants

### PR DESCRIPTION
**Pull request by alwey**
Small patch: Suggestion to get the variant information from the targeted (template) game.
I tested this with standard chess, crazyhouse and grid chess.

A new game might also "inherit" other properties from the targeted game, like time control settings, engine setups, etc. "Paste & Inherit".

### CODE REVIEW

**Comment by artoj** [comment]
I like the idea. I think the inherit should be separate function and the normal paste should ask for the variant using some method (I've discussed with Ilari but we haven't reached a conclusion yet).

Could you separate this functionality to its own menu item?

**Comment by alwey** [comment]
OK, I will try to come up with an additional function.

**Comment by alwey** [comment]
Related to issue #285

**Comment by alwey** [comment]
The "Paste & Inherit" functionality takes more effort than initially anticipated. So I will open a new PR for that.

I would suggest to use the patch above to amend the normal Paste functionality. For many users the patch will make no difference, playing standard chess only. But for variant players I guess it would be helpful.

**Comment by ilaripih** [comment]
Okay, I'll merge this one in the meantime because it's still an improvement over the current functionality and probably intuitive for most users.

**Pull request merged**
