### PR TITLE
fathom tbprobe.c: include x86intrin.h only for x386-compatible builds

### PR DESCRIPTION
**Pull request by alwey**
This patch avoids problem #204.

### CODE REVIEW

**Comment by artoj** [comment]
Could this be applied to the upstream project and then we could pull the update?

**Comment by alwey** [comment]
In the end this would be more effective of course. For now the patch will help non-x86-users of cutechess, so I should suggest to apply it.

I'll also ask @basil00 to include it upstream in order to avoid regressions.

**Comment by alwey** [comment]
I just checked upstream there already is a related PR, 11 months old:
https://github.com/basil00/Fathom/pull/12

**Comment by artoj** [comment]
Hmm.. can we just remove the header? We define `TB_NO_HW_POP_COUNT` in tbconfig.h

**Comment by alwey** [comment]
Ah, good point. Are we missing anything?

**Comment by ilaripih** [comment]
I've also added quite a few fathom patches directly to Cute Chess so I think we could remove the header completely; we're not going need a faster popcnt.

**Comment by artoj** [comment]
Indirectly related to this: we should have some type of automatic ARM builds available as well. In general there isn't much machine dependent code in Cute Chess but still it would be good to be sure...

**Comment by ilaripih** [comment]
I removed the header.

**Pull request closed without merging**
