### PR TITLE
Replace the Gaviota tablebases with Syzygy.

### PR DESCRIPTION
**Pull request by basil00**
This allows for:
    - Up to 6 piece tablebase adjudication.
    - Proper handling of the 50 move rule.

The implementation uses https://github.com/basil00/Fathom which is included as a "3rd party library".

See also #181, #68 and [the TCEC9 superfinal game 17 controversy](http://talkchess.com/forum/viewtopic.php?t=62145).

### CODE REVIEW

**Comment by ilaripih** [comment]
Wow, that's awesome! I've been planning on doing this for a while but have been too busy lately. I'll do a code review of the CuteChess/C++ parts (not Fathom) on Monday. If you check the CI reports you'll see that the GCC builds are currently failing: https://travis-ci.org/cutechess/cutechess/jobs/177367488
Looks like the problem can be fixed by compiling Fathom with `-std=c99`.

**Comment by ilaripih** [comment]
I also noticed this Fathom issue: https://github.com/basil00/Fathom/issues/13

Cute Chess runs each game in its own thread so it can make multiple `tb_probe_root` calls in parallel. Those calls should be protected by a `QMutex`.

**Comment by basil00** [comment]
> Those calls should be protected by a QMutex.

Yes you are right -- I'll fix this and the gcc issue when I have some more free time.

Another (currently unimplemented) idea is to make TB adjudication depend on whether the engines themselves support TBs.  Quoting [Ronald de Man](http://talkchess.com/forum/viewtopic.php?t=62145&postorder=asc&start=170):

`I personally don't think 6-piece TB adjudication is a good idea if one of the engines does not use TBs. There are many 6-piece positions that (some) engines are not able to play correctly, so adjudicating those is helping TB-less engines too much. This problem also exists for 5-piece positions, but to a much smaller extent.`

The question would be how to detect an engine's TB configuration, e.g. via UCI options?

**Comment by ilaripih** [comment]
I think the operator/user just has to know what TBs the engines can use and set the adjudication rules accordingly. It is possible to detect the engines' tablebase settings but they're not fully standardized.

**Comment by ilaripih** [comment]
I reviewed the rest of the code (excluding the 3rd party stuff) and it looks good. So the mutex and compilation flag are the only issues.

**Comment by basil00** [comment]
> I think the operator/user just has to know what TBs the engines can use and set the adjudication rules accordingly. It is possible to detect the engines' tablebase settings but they're not fully standardized.

Yes - I think it might be worthwhile to add an extra engine option that can be used to disable TB adjudication for specific engines, e.g. something like:

    tbadj=[on | off]

The default is `on` provided TBs are available.  I might work on a proposal as a separate PR.

**Comment by basil00** [comment]
> I reviewed the rest of the code (excluding the 3rd party stuff) and it looks good. So the mutex and compilation flag are the only issues.

Appears to now be fixed.

**Pull request merged**
