### PR TITLE
Nice arrow

### PR DESCRIPTION
**Pull request by kdave**
Draw nicer move arrow, similar to lichess.org arrows. Second patch has images for preview, not intended for merge.

### CODE REVIEW

**Comment by artoj** [comment]
Looks good to me.

Ping @ilaripih

**Comment by ilaripih** [comment]
Agreed, looks good. Can you remove the "Add arrow previews" commit and I'll merge this?

**Comment by kdave** [comment]
Sure, commit removed and pushed.

**Comment by tissatussa** [comment]
So you are going to change the look of the yellow move arrow .. can there also be an option (in Settings / General) to en/disable the arrow ? That would be nice. I think other people had this request also ..

**Comment by kdave** [comment]
There is a setting: Tools -> Settings -> General -> Show move arrows [x]

**Comment by kdave** [comment]
Although, what's common on web chess servers is that the last move is only denoted by hilighted squares, the arrows are user-drawn. I think people are used to this and I'd like to bring it to cutechess too but I realize this may be intrusive and breaking the current visual style.

**Comment by tissatussa** [comment]
@kdave !? I'm using Cute Chess v1.2.0 on Xubuntu 22.04 and i see no such option ..

CuteChess_settings

**Comment by kdave** [comment]
I see, it's a new option added after 1.2.0, I was running it from git.

**Comment by tissatussa** [comment]
> I see, it's a new option added after 1.2.0, I was running it from git.

@kdave !? how can that be? v1.2.0 is the latest version ..

**Comment by artoj** [comment]
There has been a lot work in Git since v1.2.0. We haven't released 1.3.0 because we have problems in our release process (outlined in https://github.com/cutechess/cutechess/issues/722) which I've been fixing for the past months. We're slowly getting there but not yet.

**Comment by tissatussa** [comment]
@artoj respect .. i have no problems with 1.2.0

**Comment by artoj** [comment]
Merged, thanks!

**Pull request merged**
