### PR TITLE
nullptr in projects/lib/src/tournament*

### PR DESCRIPTION
**Pull request by rwst**

### CODE REVIEW

**Comment by artoj** [comment]
This no long applies cleanly to master. Can you rebase it?

**Comment by artoj** [comment]
Unfortunately this not correct. You used merge and not rebase... see here: https://github.com/cutechess/cutechess/network compare your **newnullptr7** branch to other two to see what I mean.

**Comment by rwst** [comment]
I never rebase branches I have uploaded somewhere. But I'll upload a new one.

**Comment by ilaripih** [comment]
I rebased and merged the pull request. As you can see, the commit history is now nice and linear thanks to the rebase. I think in the future we should always rebase pull requests before merging them, even if the commits apply cleanly to master.

**Pull request closed without merging**
